[project]
name = "python-jupyter-notes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.5.2",
    "jupyterthemes>=0.20.0",
    "numpy>=2.4.1",
]
